[package]
name = "vmod_counters"
version = "0.0.0"
publish = false
edition.workspace = true

[dependencies]
varnish = { workspace = true, features = ["ffi"] }

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
