[package]
name = "vmod_vdp"
version = "0.0.1"
edition = "2021"

[build-dependencies]
varnish = { path = "../.." }

[dependencies]
varnish = { path = "../.." }
varnish-sys = { path = "../../varnish-sys" }

[lib]
crate-type = ["cdylib"]
