[package]
name = "vmod_example"
version = "0.0.1"
edition = "2021"

# if you copy this into a standalone repository,
# replace `{ path = "../.." }` with `"0.0.18"`
[build-dependencies]
varnish = { path = "../.." }

[dependencies]
varnish = { path = "../.." }

[lib]
crate-type = ["cdylib"]
